### ISSUE TITLE
ZIP code not returning anything

### ISSUE THREAD

**Issue by dfosco** [vtex-apps/shipping-calculator#5]
@amoreira Have you finished the implementation in this component?

**Comment by dfosco** [comment]
@amoreira @tamorim Here's the console on beta and local:
![image](https://cloud.githubusercontent.com/assets/3229933/12199809/1b56fcba-b602-11e5-932a-053a82a4dc3f.png)

**Comment by tamorim** [comment]
@dfosco you were running an old version, so thats deprecated.
